export const students67=[
    {
        sno:1,
        name:"ankit",
        phone:'875145854',
        course:"java",
        batch:"6pm"
    },
    {
        sno:2,
        name:"dev",
        phone:'875145854',
        course:"mern",
        batch:"6pm"
    },
    {
        sno:3,
        name:"ravi",
        phone:'875145854',
        course:"java",
        batch:"6pm"
    },
    {
        sno:4,
        name:"ansu",
        phone:'875145854',
        course:"mern",
        batch:"6pm"
    },
    {
        sno:5,
        name:"anjali",
        phone:'875145854',
        course:"react",
        batch:"6pm"
    },
    {
        sno:6,
        name:"punit",
        phone:'875145999',
        course:"mern",
        batch:"6pm"
    },
    {
        sno:7,
        name:"punit10",
        phone:'875145999',
        course:"mern",
        batch:"6pm"
    }
];